### ISSUE TITLE
Unmatched bracket heights? Is this expected?

### ISSUE THREAD

**Issue by aasutossh** [agarick/agave#10]
![image](https://user-images.githubusercontent.com/18498932/64107667-c4af6f00-cd9a-11e9-8723-1054e47de5a1.png)
The image shows the unequal height of brackets.
Is this expected?

**Comment by blobject** [comment]
No, definitely not. Thanks for reporting this. Could you please also tell me with which environment, program, font version, and font size you witnessed this behavior?

**Comment by aasutossh** [comment]
It is windows cmd.exe; 
font version 13(latest);
size is 24 but I could see this even on font size 14 or so.

I get the same thing in VS Code
![image](https://user-images.githubusercontent.com/18498932/64138010-c15bc800-ce1a-11e9-99b6-93dc397e1e2b.png)
font size 14.

**Comment by iozsaygi** [comment]
Hey, this issue is on point! I am also having this problem in Visual Studio Community 2019.
Here is the example screenshot.
![asd21](https://user-images.githubusercontent.com/36489581/64184586-56d77600-ce74-11e9-930c-9740ad44a18d.png)
I was going to open a new issue about that but i tought that is intended.

**Edit:** The font size is 10

**Comment by blobject** [comment]
The newest release ([version 14](https://github.com/agarick/agave/releases/tag/v14)) hopefully fixes most use cases.

The following is more information about the issue.

**Problem:**

Hinting (both FontForge's native autohinter and in ttfautohint) does not seem work on reference glyphs. By "reference glyph" I mean the result of that FontForge functionality whereby a codepoint refers to another codepoint rather than importing from its own vector outline source file.

**Current solution:**

References have been eliminated in favor of an actual SVG import. For instance, in version 13 and lower, the glyph for `)` was simply a reference to its matching `(` with just the shape inverted. Now, in version 14, this reference has been removed, the SVG outline of `(` has been flipped and saved into its own file, and then the file has been imported into the glyph for `)`.

**Note:**

The solution has been applied only to the more frequently used glyphs (ie. `)`, `]`, `}`, `>`, `»`). There are too many reference glyphs in the font for a pervasive application of the solution to be practical. Also, I still do not fully understand why hinting issues occur for reference glyphs and why only on Windows. As such, this should be thought of as a temporary or partial solution. Still, if this solves your particular use case, please close the ticket.

**Possibly related:**

- be5invis - Iosevka - issue 266: "Bracket alignment issue"
- google - fonts - issue 632: "Nunito Character Sizes Inconsistent with Certain 'font-size' Values"
- https://forum.glyphsapp.com/t/a-hinting-issue/9105

**Comment by iozsaygi** [comment]
Hey
Thanks for releasing new version of Agave.
I removed the old version that i have and installed the version 14.
I can definitely say that it fixed the problem in **Visual Studio Community 2019**. I have no idea about other IDE's or text editors.
Thanks.

**Comment by aasutossh** [comment]
@agarick you are on **fire**.

**Comment by aasutossh** [comment]
Also closing the issue as it is fixed.
