### ISSUE TITLE
Misalignment and gaps in box-drawing characters

### ISSUE THREAD

**Issue by traws0** [agarick/agave#12]
Hello! First of all, thank you for this awesome font!

My only issue with it is the gap in box-drawing characters.

An image to illustrate:

![compare](https://user-images.githubusercontent.com/7069042/67637325-2cc09400-f8b8-11e9-8e86-be2cbe2d2b53.png)

This is in Windows 10, using Notepad and Agave version 14.

**Comment by blobject** [comment]
Thank you @traws0 for using agave and opening this issue. I will take a look at this soon

**Comment by blobject** [comment]
Just wanted to mention that I tried tackling this issue during the weekend but failed to make much progress. I'm going to need some more time researching details and comparing with known good fonts like Consolas and Menlo.

The initial thought that came to mind was similarity to the behavior of powerline glyphs (namely, that box-drawing glyphs also obey global limits rather than the default grid dimensions): https://github.com/agarick/agave/issues/3#issuecomment-471358312 . But that doesn't seem to be the problem here.

See also:
- https://graphicdesign.stackexchange.com/questions/66605/how-do-i-make-sure-the-unicode-box-drawing-characters-work-properly-in-my-font
    The exact issue was also raised on stackexchange but sadly has no accompanying solutions.
- https://github.com/Alhadis/Menloco
    This project patches Monaco with Menlo's box-drawing glyphs.

**Comment by blobject** [comment]
@traws0  
Sorry for getting back to this issue so late.

**Changes summary**

I think some improvement has been made with the [latest version 15](https://github.com/agarick/agave/releases/tag/v15).
But there are still some tweaking to be done.

I've also added a few new glyphs for box-drawing, the ones with lines where parts of them are thicker. This doesn't exactly pertain to the issue, but I'm mentioning it anyway.

**Results**

This is a screenshot (windows notepad, size 24 on the left, and same text at size 11 on the right):

![box_win_24_11](https://user-images.githubusercontent.com/15623001/86521934-08f61a80-be57-11ea-9d18-42df40ab6937.png)

As you can see, the gaps are still there at smaller sizes (but hopefully less than before), while at larger sizes things look smoother. I've obviously missed something but it's a bit difficult to pin down. It might be due to some global dimension setting which I have so far been afraid to fiddle with too much.

On linux (emacs gui), things look a lot better, but still not perfect:

![box_linux](https://user-images.githubusercontent.com/15623001/86521971-8b7eda00-be57-11ea-8a3a-4b847c4084f2.png)

**Details**

It turns out that the global-grid-dimensions issue mentioned in the [previous comment](https://github.com/agarick/agave/issues/12#issuecomment-552395859) was indeed the problem (or at least part of the problem). I enlarged the dimensional limits of the box-drawing glyphs, and that has helped.
  - Here, "enlarged" means only that I overshot the proper 1024x2048 dimensions.
  - And by "box-drawing glyphs" I refer to the lines, blocks, and corners: 2500-25a1, 25e2-25e5).

**Comment end**

Thanks; hope this works better. I'll appreciate any feedback, and keep trying to make this look perfect -- but how long that will take, I can't say for sure.

**Comment by traws0** [comment]
Thank you very much for your effort in fixing this issue! It is now much better. I understand it must be difficult since most programming fonts seem to get this wrong. Fira Code and Lucida Console are examples of fonts that get it right.

In my win10 machine, I see some font sizes that are already perfect (12, 16), while others still retain a smaller gap (14, 20). I will probably use a perfect fontsize for now. If it proves too much effort is needed to close those small gaps, please feel to close this issue since the situation is already solved under some conditions (OS and font size).

**Comment by blobject** [comment]
Glad to hear that the slight improvements do help. I will definitely take a look at Fira Code and Lucida Console and try to get this right.

And thanks for your wonderful issue reporting - concise, thorough, and considerate. It's a pleasure.

**Comment by blobject** [comment]
With the [latest version 16](https://github.com/agarick/agave/releases/tag/v16), no gaps seem to appear at any size, on windows or linux. I am unable to test on mac.

Following the other fonts I looked at, including Consolas, Menlo, and Fira Code, I used the (somewhat nasty-tasting) strategy of overshooting beyond the specified glyph boundaries. Lucida Console sticks to the bounds, but they instead cut off a vertical metric (specifically Typo Ascent), which I am loath to do. The solution isn't neat but it's the best I can do with my current knowledge of glyph height metrics, and the results don't look too bad. (These other fonts even have gaps on linux, but agave doesn't :-)

I will close this issue, but please reopen it if you see residual problems, or create a new issue for any related problems.

These are some residual problems that I consider separate issues:

- On linux, the corner glyphs sometimes look hazy in relation to a straight horizontal glyph next to it.
- Shading (25%, 50%, 75%) glyphs and block glyphs still have gaps. I still need to consider how best to fix these: https://github.com/agarick/agave/issues/14

**Comment by blobject** [comment]
A few further fixes and additions made. See https://github.com/agarick/agave/issues/14
