### ISSUE TITLE
lowercase letters (f,i,j,t) should be more consistent

### ISSUE THREAD

**Issue by shabahengam** [agarick/agave#16]
Look at the picture
![image](https://user-images.githubusercontent.com/53096747/87828533-609e7800-c892-11ea-9380-c76fecc3c0cb.png)
as you see the lowercase `f,i,j,t` are not in the same "wave".for more info you can read [this reply](https://github.com/agarick/agave/issues/15#issuecomment-660262304)

PS: @agarick  I couldn't come up with a better title.if you think its not good you can change that.

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v22

Looking back at this, I remember that the bar on `f` was slightly lowered to make the glyph a bit more readable. The position of the bar was not aligned to `i`, `j`, or `t`, but it wasn't completely random either, having been aligned to parts of other glyphs.

But looking at it now, the consistency is probably better than the readability, and the difference is so small that the latter is not that much affected anyway.
