### ISSUE TITLE
RFC: change lowercase l letter to make it more distinguish from number 1

### ISSUE THREAD

**Issue by shabahengam** [agarick/agave#17]
I think the current lowercase `l` is too similar with number `1`.I have two suggestion
**1.** erase the left-bottom part of the current `l` to make it more distinguish
left is current version - right is modified by me in gimp :)
![lowl1](https://user-images.githubusercontent.com/53096747/87829257-e838b680-c893-11ea-8045-51b8206e3313.png)

**2.** borrow the lowercase `l` from ubuntu mono font.
In my eyes agave looks a bit similar with [ubuntu mono font](https://design.ubuntu.com/font/) so maybe we can barrow the lowercase `l` from that.
left is current version - right is lowercase `l` from ubuntu mono font
![lowl2](https://user-images.githubusercontent.com/53096747/87829268-eec72e00-c893-11ea-9b51-b96ab4935391.png)

**Comment by blobject** [comment]
Thanks for creating the issue.

However, I don't think I will fix this issue because this was a decision made when first coming up with designs for `l` and `1`. Namely, they were designed specifically to not resemble each other.

True, agave's `l` does look like `1` in some other fonts (eg. Courier), but my hope was that the user of agave would get accustomed to how the `1` looks and be able to distinguish it from the `l`, that is, within the context of agave.

If you do use agave alongside another font, then this could indeed be a problem, but otherwise I am leaning towards leaving the designs as is.

Let me know what you think.

**Comment by blobject** [comment]
Oh, and to give some reasoning behind the design itself:

I wanted the simplest designs for `l` and `1` (eg. avoid curves whenever possible) while still being distinguishable. And in the context of agave, I was not a fan of the "tilted" feeling that the andale-mono-style and ubuntu-mono-style `l`'s gave.

So it came down to where to put the "feet" (the bar at the bottom). I could put them on `l` or on `1`. I chose to put the feet on `l` because `1`'s head has an angle, which would make things look a little more "busy" than putting it on `l`.

As for the "head" on `l`, that was more of a whimsical decision, but I felt it was necessary in order to distinguish `l` from `|` or the "floor" glyph. And a straight vertical bar with feet on both sides but no head just looks weird.

**Comment by shabahengam** [comment]
OK,I close the issue.thanks for explanation.
