### ISSUE TITLE
Appreciation for making Agave

### ISSUE THREAD

**Issue by astrolemonade** [agarick/agave#18]
Hi !
My name is Catalin, I am a CS student ! I begin by saying I used so many fonts over the years in my programming environments, commercial and non-commercial ! I was obsessed to find the one that I like and stick with it! Easy to say, hard to do ! I used so many fonts that I can recognize them from screenshots !

Agave was almost always in my view but for some reasons I didn't test it too much(like in a real scenario, just some programming font test app).I recently rediscovered Agave font and I must say I feel sorry I didn't rediscovered earlier. It makes programming much more pleasant and also clean ! I now use it for all my projects and it feels good, it's like I feel the passion that was put into this and also my eye strain reduced significantly!
I understand why the dev process is a little bit irregular, time is everyone's enemy and best friend at the same time !

Looking forward to seeing this project evolve and become better(the italics and bolds would be a great feature) !
Thank you for your amazing work! If there is anything I can do as a programmer don't hesitate to ask ! I feel like supporting this project would be a great idea !
A friend you haven't made yet,
Catalin

**Comment by blobject** [comment]
Hi Catalin, I'm a CS student as well and it's nice to meet you, albeit online.

I want to sincerely thank you for using agave and giving feedback, and I'm so glad your experience with the font has been positive. I'll try to make improvements as I can and as user feedback comes in. Making bold/italic variants is one of those things that requires a stretch of dedicated time and I haven't been able to find that yet, but hopefully will soon.

To respond to the "passion" that you mentioned, I remember lying on my parents' couch for literally a full summer, standing up only to go to the bathroom. Had a laptop on my belly and inkscape on the screen. I don't know what came over me during that time, but there was a distinct urgency to create a font that had strict geometric regularity. One might call it obsession, but I like to think inspiration. The fact that the design turned out usable at all and even liked by others makes me beyond happy.

That summer-on-the-couch is a lovely memory and your message reminds me of it. Thank you. I hope you enjoy your studies and also experience many moments of focus, dedication, and passion.

**Comment by astrolemonade** [comment]
Thank you ! The story was lovely, I am grateful that you did what you did and I agree with that "urgency", I have that kind of moments at some time, the need of doing something for my soul !
Do you have any other ways of communication where we can interact more ? If you want, of course !

**Comment by blobject** [comment]
You can reach me at the email address shown on my profile page. I'd be happy to discuss agave further or other public github projects.

**Comment by kajukenbo** [comment]
Just to pile on I appreciate this font as well.
The as a Unix guy, the clarity of - vs ~ and { vs ( as used in awk seems to be ignored in a lot of "programmer fonts."

Thank you for your efforts.

**Comment by blobject** [comment]
Appreciate the feedback, @kajukenbo

I also can't stand it when those glyphs are hard to distinguish.

**Comment by aasutossh** [comment]
agave is getting all the love it deserves. Nice.

**Comment by blobject** [comment]
Closing, but please reopen if anyone sees fit.
