### ISSUE TITLE
Yogh looks like ezh

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#25]
The top of U+021C LATIN CAPITAL LETTER YOGH and U+021D LATIN SMALL LETTER YOGH should be round, unlike U+01B7 LATIN CAPITAL LETTER EZH and U+0292 LATIN SMALL LETTER EZH.
![Ȝȝ](https://user-images.githubusercontent.com/1124347/94581607-43e6cf00-0249-11eb-8c3a-87dc4bcbb369.png)

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/releases/tag/v25
![yoghs](https://user-images.githubusercontent.com/15623001/94861874-7dc9f800-0438-11eb-92e7-20533cc79170.png)
Not so pretty; the shape is quite difficult to fit into agave's "scheme". Might [fix up the capital Yogh](https://github.com/agarick/agave/issues/26) later.
