### ISSUE TITLE
Inconsistent baselines for glyphs with descenders and vertical stems

### ISSUE THREAD

**Issue by dscorbett** [agarick/agave#43]
Most glyphs that have descenders as well as vertical stems, such as U+014B, U+019E, and U+0220, shorten their vertical stems a bit so they float above the baseline. U+0267 LATIN SMALL LETTER HENG WITH HOOK and U+02A9 LATIN SMALL LETTER FENG DIGRAPH are exceptions.
![ɧʩŋƞȠ](https://user-images.githubusercontent.com/1124347/96490524-f093eb00-120e-11eb-8b4f-5abc90fcb6fe.png)

**Comment by blobject** [comment]
The inconsistency has been fixed in https://github.com/blobject/agave/releases/tag/v32

The rule I've settled on is: keep the baseline ~as usual~ at the usual line (ie. the line that "x" sits on), but raise the vertical stem only if there's something ~close underneath it~ directly underneath it and at close proximity, eg. u0271 (m with hook), u1fc3 (eta with ypogegrammeni).

The exception is eta because it can occur with a diacritic right below the vertical stem. Also, it's a bit more visually appealing to me.

If any of this sounds/looks strange, please let me know.

**Comment by blobject** [comment]
In v33, I've changed the rule again: always maintain a consistent baseline, with the sole exception being eta.

u0271 (m with hook) thus has its legs on firm ground now.
