### ISSUE TITLE
dot mark for i, j getting more vivid is better  

### ISSUE THREAD

**Issue by monstertango** [agarick/agave#54]
dot mark for i, j looks a little bit dimmish than . character.
my monitor is 1920x1080,
agave version is 35
![image](https://user-images.githubusercontent.com/38209036/101134718-2ae60a00-364e-11eb-9f31-7243121421a1.png)

**Comment by blobject** [comment]
Hi. I appreciate your comment and will see if this can be improved.

For the moment, I do agree that an equivalently bright tittle for `i` and `j` would be better, but am afraid that it would also break a few of agave's design guidelines.

For instance, a wider tittle might begin to look like a short bar, or not even resemble `.` or a dot. Making it taller would give us an `i` and `j` that is taller overall than all the other glyphs or, going the other way, shrink their x-heights even further. And finally, I would like to avoid the tittle and the stem touching, at all costs, even at the smallest font size. I've used fonts previously where the tittle and stem did touch, and it was quite the unpleasant experience.

So I guess the question is: is having brighter tittles worth the risk of geometric inconsistency or other perceptible drawbacks?

**edit:**

Well, actually, maybe making the `i` and `j` glyphs a bit taller overall is a concession we can make, since glyphs with other diacritics (eg. `ĩ`) sometimes overshoot the usual height as well.

**Comment by monstertango** [comment]
I think it's not good they get some geometric changes. their geometric shape is enough good.
we can see easily fonts take even smaller but bright dot for i, j . 
lower dpi has more definitely for this issue. 
I believe the best solution is somewhere.

**Comment by blobject** [comment]
If you could provide an example of a font whose dots are good in your eyes, that would greatly help me make improvements.

It is true that pixel-by-pixel rendering could be better, but this would require some time to study up on my part.

**Comment by monstertango** [comment]
My monitor seems to have 96 dpi  and 1920x1080 (HP 24fw)
Favorite size is 14 for me on the VS Code.
Here compared to Ellograph CF and Victor Mono font.
Also you can preview many popular fonts on https://www.programmingfonts.org.
![image](https://user-images.githubusercontent.com/38209036/101707792-44b0a280-3acf-11eb-987c-c31d459a53f3.png)

**Comment by blobject** [comment]
Awesome, thank you for that. (Side note: I hadn't seen Ellograph before - I do like how it plays with geometry in a similar spirit).

I expect the improvement of the tittles will come in the form of a slight centering and raising, and possibly some widening, depending on tested results. This will probably happen after the holidays.

**Comment by blobject** [comment]
An improvement has been attempted at https://github.com/blobject/agave/releases/tag/v36

Tittles were raised and enlarged slightly, nothing dramatic. Would love to hear whether you see an improvement, @eypsume

**Comment by monstertango** [comment]
Congratulations on new release!
Thanks a lot.

**Comment by blobject** [comment]
Closing, please reopen if there's anything to add.
