### ISSUE TITLE
Is there a strong reason to build/ship TTF instead of OTF?

### ISSUE THREAD

**Issue by alexmyczko** [agarick/agave#55]
Hi

Many thanks for the font, but I've gotten a bug report about the packaging how I do your font for Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977538

I've come across these things when looking around on the internet about ttf vs otf.
https://forum.glyphsapp.com/t/main-difference-between-otf-and-ttf/6743
http://www.techcybers.com/blog/ttf-otf-or-woff-font-format/#:~:text=OTF%20and%20TTF%20are%20extensions,part%20on%20the%20TrueType%20standard.
https://www.makeuseof.com/tag/otf-vs-ttf-fonts-one-better/
https://www.reddit.com/r/typography/comments/ci4nwk/otf_vs_ttf/

**Comment by blobject** [comment]
Hi! Your help packaging this font for debian is greatly appreciated.

The main reason I am using ttf is that I also use [**ttfautohint**](https://www.freetype.org/ttfautohint/) in my building process. The ttfautohint tool is a big boon for me as I still do not fully understand "hinting" and it would be too much work to try to do custom or manual hinting. The hinting is necessary for [better rendering](https://github.com/blobject/agave/issues/9) on different platforms (I think it makes the font look better on linux as well).

So for me, the more relevant question perhaps is "Why use ttfautohint instead of some other technique?" And currently, due to lack of time, I must stick with the former. I've tried fontforge's internal autohinting mechanism but there were [a few issues](https://github.com/blobject/agave/issues/14).

As for ttf vs otf, I actually don't know too much about the underlying formats/technology.

With regards to your packaging, why not just use [the finished ttf files](https://github.com/blobject/agave/tree/master/dist) supplied by this repository? Then you would not have to worry about building it yourself and any rendering problems users might encounter would be entirely my responsibility, as it should be. Debian's packaging policy seems to support this as well (according to [their wiki](https://wiki.debian.org/Fonts/PackagingPolicy#Packaging_Example)). **Note:** If you do decide to do this, please package only `Agave-Regular.ttf` and `Agave-Bold.ttf`. I am in the process of moving the other ttf files into a "dev" subdirectory

**Comment by blobject** [comment]
Addendum to the previous comment:

The finished ttf files can be acquired from the
- repository tree: https://github.com/blobject/agave/tree/master/dist

or from the
- releases page: for example, https://github.com/blobject/agave/releases/tag/v35

**Comment by alexmyczko** [comment]
Hi

You're welcome. We thank you for the font. I'm using it as my terminal font (switched from OCR-B).
Although not all my screens are "Retina" (High DPI), I think we're far away from 320x240 resolutions (~20 years), and people
don't use the font in smaller sizes. Maybe the bugreport is about that.

I'm aware of ttfautohint (for ttf only), but there's also psautohint (for otf), however it fails on your font when generating OTF with:
`ERROR: Font has neither StemSnapV nor StdVW!`

psautohint can run on these file formats: Type1/CFF/OTF/UFO

Debian (being a binary distribution) prefers to build from source. It would be no problem for me to build it your way, I just
personally prefer OTF for its binary format size (smaller than TTF, more modern and typographic features)

Are you aware of https://repology.org/project/fonts:agave/versions ?
http://screenshots.debian.net/package/fonts-agave (done with http://shell.aiei.ch/typography/)

**Comment by blobject** [comment]
Oh, I wasn't aware of psautohint. I will still need to study up on postscript and otf before considering a change to otf. One thing I saw is that postscript prefers 1000 box size, while my entire design scheme follows the power-of-two and uses 2048. And there are probably many more metrics and tweaks to consider.

The repology and specimen creator sites are also new to me. Very cool!

**Comment by fabiangreffrath** [comment]
> One thing I saw is that postscript prefers 1000 box size, while my entire design scheme follows the power-of-two and uses 2048. 

That alone should be reason enough to switch the Debian package back to the TTF format @alexmyczko .

**Comment by blobject** [comment]
I'm pretty confident that OTF would support 2048 emsize, but even so, some research is necessary before making the move. https://github.com/blobject/agave/issues/57 has been created to that end.

With regards to debian packaging, I don't think I'm in a position to direct how the packaging ought to be done but I'll try to conveniently place the source and distributed files.

In any case, I consider the original question to be answered, so I'll close this.

**Comment by fabiangreffrath** [comment]
@blobject Just want to inform you that I just uploaded v36 with auto-hinted TTF files to Debian. Happy new year!

**Comment by blobject** [comment]
Thank you. Happy
```
 ____   ___ ____  _
|___ \ / _ \___ \/ |
  __) | | | |__) | |
 / __/| |_| / __/| |
|_____|\___/_____|_|
```
