### ISSUE TITLE
agave v010 - goals/todo before official release?

### ISSUE THREAD

**Issue by dtzWill** [agarick/agave#6]
Not to rush things if they're not ready, just hoping to help see this through-- so there's a release with shiny powerline goodness among other things!

Any details left to work on? Testing to be done? :)

**Comment by blobject** [comment]
Hi @dtzWill thanks for the issue!

To be frank, there's not much of a release system in place at the moment, as this project started as a personal hobby/experiment and probably still is to be classified as such. The versioning is therefore completely subject to whim.

The current version 010 specifically does not have any clear roadmap. The current status is set at "beta" exactly because a roadmap was not fixed and because I was up in the air about what else to add. But the "beta" tag is superfluous; it makes no difference (at the moment at least) if I do away with it and just stick with incremental numbers for incremental changes.

In fact, I will do that now. Rename the current version to be just "10" . (I'll get rid of the leading 0 as well -- don't know why I presumed the versions will be three digits...) A new "release" on github will be uploaded shortly.

There was some thought a few months ago about making [bold and italic variants](https://github.com/agarick/agave/issues/5); perhaps version 11 will include bold. But besides that, no plan or request exists for agave at the moment. And no further details or testing is being considered right now. Given my current schedule, agave is basically in stagnation and I must rely on external short-term requests to motivate development.

**Comment by blobject** [comment]
Of course, if you have any suggestions or requests, please let me know.

**Comment by blobject** [comment]
Just to be clear, I am adopting an incremental version release system that publishes changes as soon as they are made. Version numbers are taken from the ordered set of natural numbers. And the delimiting of a version is subject to whim.

- So for instance, I recently started making use of ttfautohint. That alone caused agave to go from version 12 to 13. You can consider version 13 to be the newest "official" release at this moment.

All this is probably not such a great idea, but as this is a one-person project, I want to make it as responsive and least costly as I can, even if that means more risk of temporary instability for the user.

Testing is currently a bit of a problem because no formalisations are in place. I will look around the web for scripts or frameworks that can help test rendering on different sizes, applications, platforms, etc. Not sure when this will be done though.

Finally, there are the questions of "what is there to do" and of motivation. I feel these have been answered already. Issue #5 is the only goal in view for the moment, but I am always open to user requests.

**Comment by blobject** [comment]
Closing for now. Please reopen or create new issues as you see fit.
