### ISSUE TITLE
ligatures support

### ISSUE THREAD

**Issue by MadadiSaeed** [agarick/agave#65]
Hi. Thank you for this nice font. Do you have future plan to add ligatures ?

**Comment by blobject** [comment]
Hello. Thanks for using the font. Please refer to https://github.com/blobject/agave/issues/11

tldr: I do not plan to add ligatures due to perceived flaws inherent in the idea of ligatures and also due to lack of manpower. That said, there may be external projects that do this, eg. https://github.com/pavel/agave-code

I'll close this as duplicate, but please reopen or comment in the linked issue if you have more to add.
