### ISSUE TITLE
Question about baseline and vertical alignment of caps/numbers

### ISSUE THREAD

**Issue by kkga** [agarick/agave#66]
Hello,

I've been using agave for a few weeks and I'm quite enjoying it. Thank you for this beautiful work.

One thing that's been bothering me is the unusual treatment of baseline (it's higher that in other typefaces) and how it affects the vertical alignment of caps and numbers.
I'm pretty sure that it's by design, so I'm curious what led you to this decision and if there are any drawbacks of having a more traditional baseline.

Here's a comparison with Cascadia Code and PragmataPro to illustrate what I mean.
In the first 2 typefaces the baseline is lower, so caps and numbers are vertically centered across the line height.
In agave, the baseline is noticeable higher, so caps and numbers appear "off-center" vertically.

![image](https://user-images.githubusercontent.com/1460122/123631950-dc28d900-d806-11eb-8386-d57ae3c9a461.png)

P.S. I've tried adjusting the vertical offset of characters in my terminal. While it does make the characters centered vertically, it also breaks the alignment of box-drawing characters, so I had to revert this change back to default.

**Comment by blobject** [comment]
Hi, thanks for your feedback.

You're right -- the baseline setting may not be standard, at least from an ASCII point of view, but it was nevertheless intentional. One of my design priorities was to keep all parts of a glyph within its box and not overshoot. And because some languages have characters with low diacritics/descenders (eg. "tilde below i" u1e2d) I raised the baseline for the sake of regularity.

As you note with the (neat) screenshot you provided, uppercase and numeric glyphs appear centered in the first two fonts, but with agave, only the lowercase glyphs are vertically centered. Also, if you look at the "Ey" pair in the first highlighted line, the "Ey" pair (together) is vertically centered for agave but slightly low for the other two fonts.

I realise this may not be ideal for the viewer but in terms of design, it was the most regular, x-height-maximising, non-box-overshooting arrangement I could come up with. I'm not sure how/whether to improve this, but changing the baseline now will take quite a bit of recalculating and design work. I'd still love to hear your suggestions or what you think.

**Comment by kkga** [comment]
Thanks for explanation!
Yeah I can see now how this solution lets you maximize the x-height while keeping the line-height as compact as possible. This "readable compactness" is the reason I love this typeface in the first place, so I think I can live with the non-standard baseline :)

Thanks again, closing this.
