### ISSUE TITLE
Doesn't work on Visual Studio Community 2019.

### ISSUE THREAD

**Issue by iozsaygi** [agarick/agave#7]
Hey!
I just fell in love with Agave. Trying to make it work in **Visual Studio Community 2019** but i've failed.
**(Visual Studio displays different font (Courier New for example) when i choose Agave from settings interface)**
Does someone know workaround or fix for that?
Thanks.

**Comment by blobject** [comment]
Hi, thank you for using agave. I will see what I can do, once I get my hands on a windows machine.

**Comment by blobject** [comment]
My apologies for taking so long to look into this.

The latest version 11 of agave should work now in VSCommunity (and VSCode, etc.) on Windows. The font will be under the name "Agave" (not "agave"!). Also, **please make sure to delete any old versions of agave before installing the new one**.

The issue was caused by the fact that I had named the regular variant `r`. This is apparently not standard. As soon as I changed the variant name to "Regular", Windows applications started to recognise the font properly (for example, before the fix, VSCode would recognise `agave r` but not `agave`).

Furthermore, I capitalised the name to be "Agave" just to keep things consistent for font detection. I might still prefer the lowercase "agave" in documentation and casual use though.

One more side note. I noticed that VSCommunity renders agave rather poorly, with jagged edges and inconsistent stroke widths (things looks much nicer in VSCode). I could not fix this easily. If you experience the same problems, please open a new issue.

**Comment by iozsaygi** [comment]
Hey thanks for reply.
I fixed the problem with the steps below. (Just like you recommended)
1) Delete the old version of agave.
2) Downloaded new version of agave from [here](https://github.com/agarick/agave/tree/master/dist).
3) Installed the new font that i downloaded and it works in VSCommunity now.

However just like you mentioned VSCommunity renders the font poorly so i am going to open a new issue for that.

Thanks.
