### ISSUE TITLE
Some editors can't find agave

### ISSUE THREAD

**Issue by aasutossh** [agarick/agave#8]
Hi, as you already know, agave is the one. So I am trying to use it with a bunch of editors.

Android Studio doesn't find agave, same with Python IDLE.

But others, like gVim, PyCharm, IDEA, Sublime Text, VS Code can locate the font.

Are those specific software problems or font issues?

**Comment by blobject** [comment]
Hey there. Thank you for opening this issue. I will have to take a look at what's going on here. I'll also treat this issue in conjunction with https://github.com/agarick/agave/issues/7, as a single item. (ie. a similar problem occurs with VS Community.)

**Comment by aasutossh** [comment]
Yeah but those editors don't even list the font.

**Comment by blobject** [comment]
I see. I will see if I can reproduce and fix this.

**Comment by aasutossh** [comment]
> 
> 
> I see. I will see if I can reproduce and fix this.

Let me know if I can be of any help.

**Comment by iozsaygi** [comment]
@DrDonkey Visual Studio Community lists the font but it does not apply the font to the editor when i choose Agave. It activates some different font instead. (Courier New for example)

**Comment by aasutossh** [comment]
@iozsaygi yeah, I noticed it too on VS Code Insiders.

**Comment by DrDonkey** [comment]
Python idle can't find it too.

**Comment by aasutossh** [comment]
I got the beta version of Android studio and amazingly it is able to find agave.
Finally, I am complete.

**Comment by iozsaygi** [comment]
Congrats! Hope VS will be able to find it too. (At some point)

**Comment by aasutossh** [comment]
> 
> 
> Congrats! Hope VS will be able to find it too. (At some point)

Yeah. People should try beta or dev builds to see if it works for them or not.
**For the sake of completeness of this issue I am closing this one.**

**Comment by blobject** [comment]
Great to hear! I'll try to find a fix for the other editors - hopefully within this weekend. Thanks for the testing and feedback @iozsaygi @DrDonkey

**Comment by blobject** [comment]
I understand this issue is closed, and do apologise for the late follow-up, but just wanted to leave a comment saying that I was **unable** to reproduce the issue.

I am running a recent & near-vanilla instance of Archlinux + KDE (ie. anything font-rendering-related was untouched after the installation of the default `xorg` and `plasma-desktop` packages). I installed agave manually, then opened IDLE and Android-Studio, and found that both applications were successfully locating and applying the font.

> **NOTE:** the font name "agave" is all-lowercase, so IDLE, for example, had "agave" near the bottom of its font listing due to its ordering Capital names first. I hope that was not the cause of this issue.

Some screenshots:

agave installed by placing `agave-r.ttf` in a manually created `~/.fonts` folder:

![image](https://user-images.githubusercontent.com/15623001/63803536-71aa6780-c915-11e9-992c-10be14c4a1c9.png)

Python's IDLE 3.7.3:

![image](https://user-images.githubusercontent.com/15623001/63801793-69502d80-c911-11e9-859a-755ef0015b0c.png)

Android-Studio stable 3.5.0.21 (https://aur.archlinux.org/packages/android-studio/):

![image](https://user-images.githubusercontent.com/15623001/63801809-72d99580-c911-11e9-8749-4f7a0402edc5.png)

I have not tested the other well-behaving editors mentioned in the opening comment, but did try some other apps already locally installed, including Emacs, GIMP, Inkscape, and Termite. They all had no trouble showing agave.

In case you'd like me to look into this issue more, I would appreciate some more information on what desktop environment was used (if any), what the procedure was for installing agave, and pertinent software versions (editors, fontconfig, DE). Otherwise, I will leave this issue as-is and focus on what the deal is with Visual Studio over in Wimdows land. Thanks!
